### ISSUE TITLE
Does'n work with jsonwebtoken >= 8.0.0

### ISSUE THREAD

**Issue by sgtram** [Livefyre/livefyre-nodejs-utils#12]
jsonwebtoken >= 8.0.0
Error: Expected object
    at validate (/node_modules/livefyre/node_modules/jsonwebtoken/sign.js:34:11)

https://github.com/auth0/node-jsonwebtoken/blob/master/sign.js#L33

**Comment by devongovett** [comment]
Should be fixed by #10. Released in v2.0.8.
